var firstname="Ojaswi";
var lastname="Goel";
var fullname=firstname.concat(lastname);
console.log(fullname);
document.getElementById("Ex1").innerHTML=fullname;
var fruitarray=["apple","grapes", "mango"];
fruitarray.reverse();
var lengtharray=fruitarray.length;
console.log(lengtharray);
document.getElementById("Ex2").innerHTML=lengtharray;
var firstelement=fruitarray[0];
console.log(firstelement);
document.getElementById("Ex3").innerHTML=firstelement;
var numberarray=["7","17","27","10","1"];
var maxnumber=Math.max.apply(Math,numberarray);
console.log(maxnumber);
document.getElementById("Ex2").innerHTML=maxnumber;
fruitarray.unshift("Guava");
console.log(fruitarray);
document.getElementById("Ex2").innerHTML=fruitarray;